on:
  workflow_dispatch:
name: Build
jobs:
  make:
    name: Build Sileo
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Bootstrap Procursus
        uses: w2599/procursus-action@main
        with:
          packages: zstd ldid xz-utils bzip2 lz4
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Add Procursus to PATH
        run: |
         # echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH

      - name: Select Correct Xcode (14.2)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app

      - name: Build Sileo Nightly (iphoneos-arm64)
        run: |
          make clean package DEBUG=0 ALL_BOOTSTRAPS=1 SILEO_PLATFORM=iphoneos-arm64
          # make clean package NIGHTLY=1 DEBUG=0 ALL_BOOTSTRAPS=1 SILEO_PLATFORM=iphoneos-arm64

      - name: Upload Latest Artifact
        id: sileo-latest-upload
        uses: actions/upload-artifact@v3
        with:
          name: sileo_Latest
          path: |
            packages/*.deb
